#!/bin/bash

SSH_MACHINES="$1"

# Read from rc file if no machine is specified in commmand line
if [ -z "$SSH_MACHINES" -a -f "$HOME/.dosshrc" ]; then
    SSH_MACHINES=$(cat "$HOME/.dosshrc" | sort | xargs)
fi

# Exit if there are no machines to ssh
if [ -z "$SSH_MACHINES" ]; then
    echo "dossh: No machine to SSH to"
    exit 1
fi

function screen_title()
{
    echo "$1" | sed 's/^[^@]\+@//;s/\..*$//'
}

# If there are more than one machines (most likely read from rc file)
if echo "$SSH_MACHINES" | grep -q ' '; then
    select server in $SSH_MACHINES; do
        if [ -n "$server" ]; then
            if [ "$TERM" = screen ]; then
                DOSCREEN="screen -t $(screen_title "$server")"
            fi
            break
        fi
    done
else
    server="$SSH_MACHINES"
    if [ "$TERM" = screen ]; then
        DOSCREEN="screen -t $(screen_title "$server")"
    fi
fi

$DOSCREEN ssh "$server"
