#!/bin/bash

usage="\
Usage: evaluate [-xo] expression [expression [...]]
    -x      Print result in hex
    -o      Print result in octal
Results are printed in decimal by default"

ARGS="$(getopt -o "xo" -- "$@")"
if [ $? -ne 0 ]; then
    echo "$usage"
    exit 1
fi

eval set -- "$ARGS"

f=d
until [ -z "$*" ]; do
    case "$1" in
        -x)
        f=x
        ;;

        -o)
        f=o
        ;;

        --)
        shift
        break
        ;;
    esac

    shift
done

if [ -z "$*" ]; then
    echo "$usage"
    exit 1
fi

for i; do
    let "x = $i"
    eval "printf \"\$i: %#$f\\n\" \"\$x\""
done
