#!/bin/bash

PROGNAME="$(basename $0)"
USAGE="$PROGNAME: Usage: $PROGNAME YYYY-MM-DD"
if [ "$#" -ne 1 ]; then
    echo "$USAGE"
    exit 1
fi

GIVEN_DATE=$(date -d "$1") || exit
date -d "$GIVEN_DATE - 90 days" +%F
