#!/bin/bash

actual_rm="/bin/rm"
must="rm: Thou shalt invoke $actual_rm directly"
recursive=0

if ! which getopt >/dev/null; then
    echo "rm: This script requires GNU getopt in \$PATH"
    echo "$must"
    exit 1
fi

if ! which uuidgen >/dev/null; then
    echo "rm: This script requires uuidgen utility in \$PATH"
    echo "$must"
    exit 1
fi

if [ -z "$*" ]; then
    command rm "$@"
    exit
fi

saved_args=("$@")
eval set -- $(getopt -o "rR" -l 'recursive' -q -- "$@")

if [ "$?" -ne 0 -a "$?" -ne 1 ]; then
    echo "rm: 'getopt' returned error"
    echo "$must"
    exit 1
fi

until [ -z "$*" ]; do
    case "$1" in
        -r | -R | --recursive)
        recursive=1
        ;;

        --)
        shift
        arguments="$@"
        break
        ;;
    esac

    shift
done

set -- "${saved_args[@]}"

# Check if the user specified a -r
if [ "$recursive" -eq 1 ]; then
    mark="$(uuidgen | awk -F- '{print toupper($2)}')"
    echo "rm: To proceed, enter the following text below: $mark"
    echo -n "** $arguments **: "
    read
    if [ "$REPLY" != "$mark" ]; then
        echo "rm: Command aborted"
        echo "$must"
        exit 1
    else
        $actual_rm "$@"
    fi
else
    $actual_rm "$@"
fi

