#!/bin/bash

PROGNAME="$(basename $0)"
USAGE="Usage: tarcp ARGS [-v]"

if ! which getopt >/dev/null; then
    echo "$PROGNAME: getopt not found in \$PATH"
    exit 1
fi

ARGS="$(getopt -o "v" -- "$@")"
if [ "$?" -ne 0 ]; then
    echo "$PROGNAME: 'getopt' returned error"
    exit 1
else
    eval set -- $ARGS
fi

until [ -z "$*" ]; do
    case "$1" in
        -v)
        VERBOSE=v
        ;;

        --)
        shift
        set -- "$@"
        break
        ;;
    esac

    shift
done

ARGS=("$@")

if [ "${#ARGS[*]}" -lt 2 ]; then
    echo "$PROGNAME: Not enough arguments"
    echo "$USAGE"
    exit 1
fi

DEST="${ARGS[$#-1]}"

if [ ! -e "$DEST" ]; then
    echo "$PROGNAME: Destination $DEST doesn't exist"
    exit 1
elif [ ! -d "$DEST" ]; then
    echo "$PROGNAME: Destination $DEST is not a directory"
    exit 1
fi

unset ARGS[$#-1]

tar cz$VERBOSE "${ARGS[@]}" | tar xz -C "$DEST"
