#!/bin/bash

PROGNAME=$(basename $0)
THISDIR=$( (cd $(dirname $0) && pwd) )

cd "$THISDIR"

[ -f initrc ] && source initrc

if [ -z "$PROJECT_ROOT" ]; then
    echo "$PROGNAME: \$PROJECT_ROOT is not set!"
else
    echo "$PROGNAME: using \$PROJECT_ROOT as $PROJECT_ROOT"
fi

FIND_EXPR="( -iname *.cpp -o -iname *.h -o -iname *.inl -o -iname *.s -o -iname *.cia )"
SRCDIRS="$PROJECT_ROOT/e32
         $PROJECT_ROOT/f32
         $PROJECT_ROOT/bsp/hwip_arm"
TEMPFILE=files.list

if [ ! -d "$PROJECT_ROOT" ]; then
    echo "$PROGNAME: directory $PROJECT_ROOT doesn't exist!"
    exit 1
fi

if [ -f "$TEMPFILE" ]; then
    read -p "$PROGNAME: delete and remake files.list (y/n)? "
    if [ "$REPLY" = "y" -o "$REPLY" = "Y" ]; then
        rm $TEMPFILE
        echo "$PROGNAME: building list of files"
        find $SRCDIRS -name .svn -prune -o $(echo $FIND_EXPR) -print > $TEMPFILE
    fi
else
    echo "$PROGNAME: building list of files"
    find $SRCDIRS -name .svn -prune -o $(echo $FIND_EXPR) -print > $TEMPFILE
fi

# Delete the tag file if already existing
[ -f "$TAGFILENAME" ] && rm $TAGFILENAME

echo "$PROGNAME: building tags"
# --sort=no - tags in the C file gets a precedence
if ctags -L $TEMPFILE \
        --langmap=c++:+.inl,c++:+.cia \
        --extra=+f \
        --extra=+q \
        -I __FALCON__ \
        -I NONSHARABLE_CLASS=class\
        -I EXPORT_C \
        -I IMPORT_C; then
    echo $PROGNAME: tags built
else
    echo $PROGNAME: error building tags
fi

## CSCOPE setup

CSCOPEFILENAME=cscope

if mlcscope -b -q -k -i $TEMPFILE -f $CSCOPEFILENAME; then
    echo $PROGNAME: cscope db built
else
    echo $PROGNAME: error building cs db
fi
