
if $PROJECT_LOC == ""
    echohl Error | echo "$PROJECT_LOC is not set!" | echohl None
    finish
endif

" Directory where this file lies
let s:this_dir =  $PROJECT_LOC

" Root directory for project files
let s:root_dir = "/cygdrive/f/Symbian/M04820_Symbian_OS_v9.6/src/CEDAR/GENERIC/base"

exe "set tags+=" . s:this_dir . "/" . "tags"

set path=.
exe "set path=.," . s:root_dir . "/e32/include/**"

set foldopen-=block

" Set the grep path
exe "set grepprg=grep\\ -nr\\ '$*'\\ " . s:root_dir . "\\ \\\\\\|\\ sed\\ \\\"/\\\\.svn/d\\\""

" Modify makeprg to accomodate arguments
" set makeprg=make\ $*

" Add cscope database connection
if filereadable(s:this_dir . "/cscope")
    exe "cscope add " . s:this_dir . "/cscope"
    set nocst           " Don't search the cs db, but use ctags, on CTRL-]
    set csto=0          " If at all a :cstag is performed, use the cs db rather than the tag
    set csqf=c-,t-,e-   " Use quickfix window for caller and assignment search
else
    echo "Couldn't find the cs db!"
endif

au BufRead,BufNew *.cia setf cpp
au BufRead,BufNew *.cpp,*.h,*.inl,*.cia source ~/jeenu-rep/work/vim/jeenu/symbian.vim
